### PR TITLE
Allow true async requests in Synegy and Synergy::LPC

### PR DESCRIPTION
**Pull request by wolfsage**
We do this using futures. This means Synergy::LPC isn't tied
to IO::Async (or any event framework).

Right now async is just used in damage report to speed up
its operations since it makes a number of calls (and one of
them is very slow).

### CODE REVIEW

**Comment by wolfsage** [comment]
BEHOLD! THE FUTURES!

**Comment by rjbs** [comment]
Needs a rebase. :(

**Comment by wolfsage** [comment]
Rebased :(

**Comment by rjbs** [comment]
LiquidPlanner is dead.

**Pull request closed without merging**
