### PR TITLE
Allow more formal bot address, by comma

### PR DESCRIPTION
**Pull request by tjwds**

### CODE REVIEW

**Review by rjbs — CHANGES_REQUESTED** [review]
This isn't wrong, but better would probably be to make them use the same expression.  Why is one spaced differently?  Why does only one quotemeta?  If they're the same, easier for someone to extract them to common code later (or sooner)!

**Comment by tjwds** [comment]
@rjbs Where would you put that expression?  Util?

**Comment by rjbs** [comment]
@tjwds Yeah, Util is the real fruit salad of functions.  Alternatively, it could go into Synergy::Role::Channel, which might not be a bad idea.

**Comment by rjbs** [comment]
@tjwds Last(?) nit:  Commit style is "CLASS: message" so maybe:

```
Channel role: add a common way to get the thing
Discord and Slack channels: use the common thing foo_bar
```

**Comment by rjbs** [comment]
All tests pass.  It would definitely be easy to write tests for this using Synergy::Channel::Test

**Review by rjbs — APPROVED** [review]
👍🏽

**Comment by rjbs** [comment]
This broke things.  I don't know why yet. Let's fix it tomorrow. :)

**Pull request merged**
